version: '3.8'

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio
    environment:
      # - USERID=1001
      # - GROUPID=1001
      # - USER=test
      - PASSWORD
      - ROOT=FALSE
      - MINICONDA_VERSION=py38_4.8.3
    restart: always
    volumes:
      - data:/data
    ports:
      - "8787:8787"

volumes:
    data: